### ISSUE TITLE
error when running on android 

### ISSUE THREAD

**Issue by copypasteearth** [Finnhub-Stock-API/finnhub-kotlin#1]
hello

I am trying to use this in android and it is throwing unsupported operation when I am calling for stock candles 

`val apps = apiClient.stockCandles(ticker, getResolution(interval), getStartOfDayInMillis(interval), getEndOfDayInMillis(), null)`
```
java.lang.UnsupportedOperationException: responseBody currently only supports JSON body.
        at com.finnhub.api.apis.DefaultApi.stockCandles(DefaultApi.kt:16835)
```

**Comment by nongdenchet** [comment]
hey @copypasteearth sorry for the late response. Let me have a look

**Comment by nongdenchet** [comment]
Can you try again with 1.2.0?
