### ISSUE TITLE
java.lang.NoClassDefFoundError: java.time.OffsetDateTime

### ISSUE THREAD

**Issue by Melowetty** [Finnhub-Stock-API/finnhub-kotlin#5]
Hello.
Every time when i call any method of library i get that error:
java.lang.ClassNotFoundException: java.time.OffsetDateTime

Can you help me with this problem please?

**Comment by nongdenchet** [comment]
Hi @Melowetty, can you try with 1.2.0 and let me know?

**Comment by nongdenchet** [comment]
closing due to no reply. Feel free to reopen if the issue is still happening
